[book]
title = "现代Fortran程序设计"
authors = ["Fortran-Fans"]
desciption = "面向初学者的现代Fortran教程"
version = "0.1.0"
language = "zh"
multilingual = false
src = "src"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/fortran-fans/modern-fortran-programming/tree/main/"
edit-url-template = "https://github.com/fortran-fans/modern-fortran-programming/edit/main/{path}"

[output.html.playground]
editable = false
copy-js = true
line-numbers = false

