[book]
title = "现代Fortran程序设计"
authors = ["Fortran-Fans"]
desciption = "面向初学者的现代Fortran教程"
language = "zh"
multilingual = false
src = "src"

[output.html]
mathjax-support = true

[output.html.playground]
editable = false
copy-js = true
line-numbers = false

