name: mdbook
on: 
  push:
    paths:
    - "src/**.md"
    - "book.toml"
  
  pull_request:
    branches:
    - main
    paths:
    - "src/**.md"
    - "book.toml"
    
jobs:
  pages:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook 📔
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.10'
          # mdbook-version: 'latest'

      - run: mdbook build
        
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push' && github.repository == 'fortran-fans/modern-fortran-programming' && ( startsWith( github.ref, 'refs/tags/' ) || github.ref == 'refs/heads/main' )
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book